# Generated by Django 3.1.3 on 2021-03-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
