# Generated by Django 3.1.3 on 2021-02-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_shopcard_sec_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcard',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
